### ISSUE TITLE
Error running the script

### ISSUE THREAD

**Issue by LDC-ar** [CedricGuillemet/BlenderLiveUpdate#1]
Hello Cedric!
 I hope you are doing good. I was trying to test the script but couldn't run. I'm pasting a screenshot.
https://gyazo.com/dd46fe516c5ded9f94dabadd61954648

It's something i did wrong maybe?

**Comment by CedricGuillemet** [comment]
This should be fixed now. Thank you for testing!

**Comment by LDC-ar** [comment]
No worries. It's a pleasure.
Well the script seems to run now. 
My problem is that i cannot get this to start working. I mean, to link the blender scene. I'm just starting with web development so i may find hard some stuff.
Anyways thanks for the fix.
